export async function onRequestPost({ request, env }) {
  try {
    if (!env?.NOTIFY_KV) return json({ ok: false, error: "kv_not_configured" }, 500);
    if (!env?.NOTIFY_KEY) return json({ ok: false, error: "key_not_configured" }, 500);

    // Auth
    const auth = request.headers.get("authorization") || "";
    const want = `Bearer ${String(env.DISPATCH_TOKEN || "")}`;
    if (!env?.DISPATCH_TOKEN || auth !== want) return json({ ok: false, error: "unauthorized" }, 401);

    const origin = new URL(request.url).origin;

    // Load latest items from the site (generated by fetch_ugc.py)
    const [user, group] = await Promise.all([
      fetchJson(`${origin}/data_user.json`),
      fetchJson(`${origin}/data_group.json`),
    ]);

    const items = normalizeItems(user, "Profile").concat(normalizeItems(group, "Group"))
      .filter((x) => typeof x.price === "number" && x.price > 0)
      .sort((a, b) => (a.createdTs || 0) - (b.createdTs || 0));

    const latestTs = items.length ? (items[items.length - 1].createdTs || 0) : 0;

    const lastTsStr = await env.NOTIFY_KV.get("state:last_ts");
    const lastTs = Number(lastTsStr || "0") || 0;

    if (!latestTs || latestTs <= lastTs) {
      return json({ ok: true, new: 0, sentEmail: 0, sentSms: 0 }, 200);
    }

    const newItems = items.filter((x) => (x.createdTs || 0) > lastTs);
    const newest = newItems.length ? (newItems[newItems.length - 1].createdTs || latestTs) : latestTs;

    const subject = `New UGC on sale (${newItems.length})`;
    const lines = newItems.slice(-6).reverse().map((it) => `• ${it.name} — https://www.roblox.com/catalog/${it.assetId}`);
    const bodyText = `New items on sale:\n\n${lines.join("\n")}\n\nPortfolio: ${origin}\n`;

    // Subscribers
    const aesKey = await importAesKey(env.NOTIFY_KEY);

    let sentEmail = 0;
    let sentSms = 0;

    // List keys (KV list is paginated)
    let cursor = undefined;
    for (let page = 0; page < 50; page++) {
      const listed = await env.NOTIFY_KV.list({ prefix: "sub:", cursor });
      cursor = listed.cursor;

      for (const k of listed.keys || []) {
        const raw = await env.NOTIFY_KV.get(k.name);
        if (!raw) continue;

        let rec = null;
        try { rec = JSON.parse(raw); } catch { continue; }
        if (!rec?.enc?.iv || !rec?.enc?.ct) continue;

        const payloadJson = await aesGcmDecrypt(rec.enc, aesKey);
        let payload = null;
        try { payload = JSON.parse(payloadJson); } catch { payload = null; }
        if (!payload) continue;

        const email = String(payload.email || "").trim();
        const phone = String(payload.phone || "").trim();
        const channels = payload.channels || {};

        // Email
        if (channels.email && email) {
          const ok = await sendEmail(env, email, subject, bodyText);
          if (ok) sentEmail++;
        }

        // SMS
        if (channels.sms && phone) {
          const ok = await sendSms(env, phone, `New UGC on sale: ${newItems[0]?.name || "New item"}\n${origin}`);
          if (ok) sentSms++;
        }
      }

      if (!listed.list_complete) break;
      if (!cursor) break;
    }

    await env.NOTIFY_KV.put("state:last_ts", String(newest));

    return json({ ok: true, new: newItems.length, sentEmail, sentSms }, 200);
  } catch (e) {
    return json({ ok: false, error: "server_error" }, 500);
  }
};

function json(obj, status = 200) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: {
      "content-type": "application/json; charset=utf-8",
      "cache-control": "no-store",
    },
  });
}

async function fetchJson(url) {
  const r = await fetch(url, { cf: { cacheTtl: 0, cacheEverything: false } });
  if (!r.ok) throw new Error(`fetch ${url} ${r.status}`);
  return r.json();
}

function normalizeItems(raw, source) {
  const items = Array.isArray(raw?.items) ? raw.items : [];
  const out = [];
  for (const it of items) {
    const assetId = it.assetId ?? it.id;
    const price = it.price ?? it.priceInRobux;
    const created = it.created ?? it.createdUtc ?? null;
    if (!assetId) continue;
    const createdTs = created ? Date.parse(created) : 0;
    out.push({
      assetId,
      name: it.name || `Item ${assetId}`,
      price: typeof price === "number" ? price : Number(price),
      createdTs,
      source,
    });
  }
  return out;
}

/* Encryption helpers */
function b64ToBytes(b64) {
  const bin = atob(String(b64 || "").replace(/[\s\r\n]+/g, ""));
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}
function bytesToB64(bytes) {
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]);
  return btoa(bin);
}
async function importAesKey(b64Key) {
  const raw = b64ToBytes(b64Key);
  if (raw.byteLength !== 32) throw new Error("bad_key_len");
  return crypto.subtle.importKey("raw", raw, { name: "AES-GCM" }, false, ["encrypt", "decrypt"]);
}
async function aesGcmDecrypt(enc, key) {
  const iv = b64ToBytes(enc.iv);
  const ct = b64ToBytes(enc.ct);
  const ptBuf = await crypto.subtle.decrypt({ name: "AES-GCM", iv }, key, ct);
  return new TextDecoder().decode(ptBuf);
}

/* Email providers */
async function sendEmail(env, to, subject, text) {
  // Option A: SendGrid
  if (env.SENDGRID_API_KEY && env.MAIL_FROM) {
    return sendEmailSendGrid(env.SENDGRID_API_KEY, env.MAIL_FROM, to, subject, text);
  }
  // Option B: MailChannels (no key, but your domain must be allowed)
  if (env.MAIL_FROM) {
    return sendEmailMailChannels(env.MAIL_FROM, to, subject, text);
  }
  return false;
}

async function sendEmailSendGrid(apiKey, from, to, subject, text) {
  const r = await fetch("https://api.sendgrid.com/v3/mail/send", {
    method: "POST",
    headers: {
      "authorization": `Bearer ${apiKey}`,
      "content-type": "application/json",
    },
    body: JSON.stringify({
      personalizations: [{ to: [{ email: to }], subject }],
      from: { email: from },
      content: [{ type: "text/plain", value: text }],
    }),
  });
  return r.ok;
}

async function sendEmailMailChannels(from, to, subject, text) {
  const r = await fetch("https://api.mailchannels.net/tx/v1/send", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      personalizations: [{ to: [{ email: to }] }],
      from: { email: from, name: "Roblox Portfolio" },
      subject,
      content: [{ type: "text/plain", value: text }],
    }),
  });
  return r.ok;
}

/* SMS provider (Twilio) */
async function sendSms(env, to, message) {
  if (!env.TWILIO_SID || !env.TWILIO_TOKEN || !env.TWILIO_FROM) return false;

  const url = `https://api.twilio.com/2010-04-01/Accounts/${env.TWILIO_SID}/Messages.json`;
  const body = new URLSearchParams();
  body.set("To", to);
  body.set("From", env.TWILIO_FROM);
  body.set("Body", message);

  const auth = btoa(`${env.TWILIO_SID}:${env.TWILIO_TOKEN}`);

  const r = await fetch(url, {
    method: "POST",
    headers: {
      "authorization": `Basic ${auth}`,
      "content-type": "application/x-www-form-urlencoded",
    },
    body,
  });

  return r.ok;
}
